### ISSUE TITLE
error:06065064:digital envelope routines:EVP_DecryptFinal_ex:bad decrypt

### ISSUE THREAD

**Issue by immjs** [Vap0r1ze/discord-remote-auth#1]
I fixed the library a bit by myself because there were previous errors but now i get this:
error:06065064:digital envelope routines:EVP_DecryptFinal_ex:bad decrypt
Help?

**Comment by Vap0r1ze** [comment]
Sorry for the very long delay, but can you give tell me what version of openssl you have installed?

**Comment by Vap0r1ze** [comment]
stale
