### ISSUE TITLE
seems like discord updated the remote auth api

### ISSUE THREAD

**Issue by neu-ma-tic** [Vap0r1ze/discord-remote-auth#7]
seems like discord updated remote auth gateway? it doesnt seem to be working with the example from the readme

**Comment by neu-ma-tic** [comment]
after messing around a bit, I got it to work with me

the new flow is as follows:
- client is sent hello
- server is sent public key
- client is sent nonce
- server is sent nonce proof
- client is sent pending remote init with fingerprint
### after scan:
- client is sent "pending_ticket" (the [data](https://gist.github.com/neu-ma-tic/87fee17f7f1c209473e7d1039dbbeeb8#file-pending_ticket-json) includes an `encrypted_user_payload` field, which was the same as the old one) **the event name and property name are changed now**
### after client approves
- client is sent a "pending_logjn" event with a "ticket" in its [data](https://gist.github.com/neu-ma-tic/87fee17f7f1c209473e7d1039dbbeeb8#file-pending_login-json)
- the client sends a POST request to `/api/v9/users/@me/remote-auth/login` with the ticket ([ex](https://gist.github.com/neu-ma-tic/87fee17f7f1c209473e7d1039dbbeeb8#file-ra-login-new-js))
after this request, discord responds with the user's token

**Comment by Vap0r1ze** [comment]
thanks for the detail

**Comment by neu-ma-tic** [comment]
i got it at walmart)

**Comment by mertushka** [comment]
I think Discord updated it again. @neu-ma-tic @Vap0r1ze

**Comment by Vap0r1ze** [comment]
> I think Discord updated it again. @neu-ma-tic @Vap0r1ze

This is when you open an issue and show your issue 😱😱

**Comment by mertushka** [comment]
> > I think Discord updated it again. @neu-ma-tic @Vap0r1ze
> 
> This is when you open an issue and show your issue 😱😱

Response data comes like this when making post request to `https://discord.com/api/v9/users/@me/remote-auth/login` 

(NodeJS Version: v18.12.1)
![image](https://user-images.githubusercontent.com/34413473/205444054-de3ec997-be06-4508-a3c8-acc5f273c967.png)

**Comment by mertushka** [comment]
> > > I think Discord updated it again. @neu-ma-tic @Vap0r1ze
> > 
> > 
> > This is when you open an issue and show your issue 😱😱
> 
> Response data comes like this when making post request to `https://discord.com/api/v9/users/@me/remote-auth/login`
> 
> (NodeJS Version: v18.12.1) ![image](https://user-images.githubusercontent.com/34413473/205444054-de3ec997-be06-4508-a3c8-acc5f273c967.png)

[PR](https://github.com/Vap0r1ze/discord-remote-auth/pull/10) solves this issue.

**Comment by neu-ma-tic** [comment]
> > > > I think Discord updated it again. @neu-ma-tic @Vap0r1ze
> > > 
> > > 
> > > This is when you open an issue and show your issue screamscream
> > 
> > 
> > Response data comes like this when making post request to `https://discord.com/api/v9/users/@me/remote-auth/login`
> > (NodeJS Version: v18.12.1) ![image](https://user-images.githubusercontent.com/34413473/205444054-de3ec997-be06-4508-a3c8-acc5f273c967.png)
> 
> [PR](https://github.com/Vap0r1ze/discord-remote-auth/pull/10) solves this issue.

thanks :+1: 
node 18 is the issue? Over the past few days I did get responses like that when working with axios, and never with node-fetch. I didn't think anything of it, and I just kept using fetch. On another machine running node 16.17.1, axios with the Discord API still works, and it returns json rather than whatever type of buffer data that is
